### ISSUE TITLE
Running the application fails in Mac

### ISSUE THREAD

**Issue by jachinte** [TylerJewell/che-electron#2]
Hello,
I am trying Che for the first time. I ran it and it works ok in the browser, however when I run the Electron app it does not work. I am on Mac Yosemite 10.10.5, with Node v5.4.1.

This is the error I am getting:
```
LSOpenURLsWithRole() failed with error -10810 for the URLs file:///Applications/eclipse-che.app/, file:///Applications/, and http://localhost:8080.
```
When I run the Electron app directly (as suggested [here](https://github.com/atom/atom/issues/3093)) I got this:
```
$ eclipse-che.app/Contents/MacOS/Electron . http://localhost:8080
dyld: Library not loaded: @rpath/libnode.dylib
  Referenced from: /Applications/eclipse-che.app/Contents/Frameworks/Electron Framework.framework/Electron Framework
  Reason: image not found
Trace/BPT trap: 5
```
Do I need to install Xcode to run che-electron?

Thanks!

**Comment by benoitf** [comment]
I got this error as well.

I then tried to recompile by myself the electron package on my Mac and then it worked.
I followed the steps to compile the electron app on https://github.com/TylerJewell/che-electron/blob/master/README.md 

and using npm run pack:osx

**Comment by jachinte** [comment]
Thanks @benoitf, it is working now.

**Comment by jachinte** [comment]
Also, the correct way to run the app in mac is (missing --args in [README.md](https://github.com/TylerJewell/che-electron/blob/master/README.md)):
````
open eclipse-che.app --args . http://localhost:8080
```

**Comment by TylerJewell** [comment]
Updated the README with these points.  Thanks @jachinte!.
