### ISSUE TITLE
Erro _xgetWireToEvent

### ISSUE THREAD

**Issue by hc3** [TylerJewell/che-electron#5]
when a try run ./eclipse-che . myip e receive an erro:
````
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.

````

**Comment by TylerJewell** [comment]
Oh wow - that looks like an old Electron issue.  I haven't checked this repo in many quarters, and looking at the stats there are a lot of GitHub stars and downloads. Maybe it's time for the Eclipse Che project to formalize the Electron client.

**Comment by hc3** [comment]
but you have an solution for this problem, you client seems to be very good, i want to test.

**Comment by TylerJewell** [comment]
Yeah, I understand. But the core engineering team at Eclipse Che started on a more formal electron desktop client. It's more sophisticated than the very basic work that I did on this repository. I do not plan to maintain this project anymore instead favoring the work that they did. It is still in a branch but you can ask them on the repository which branch the work was done so that you can compile and reuse it.
